[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "propertycrawler"
version = "0.1"

[tool.hatch.build.targets.wheel]
      packages = ["."]

[tool.pytest.ini_options]
pythonpath = [
  ".", "src/", "src/propertycrawler",
]